site_name: rcmedeiros/template
site_description:
    A TypeScript/JavaScript Node Template that does very little other than to
    demonstrate how to setup a CI/CD project.
repo_url: https://github.com/rcmedeiros/template/
edit_uri: edit/develop/docs
dev_addr: 127.0.0.1:80
markdown_extensions:
    - nl2br
    - sane_lists
    - codehilite:
          linenums: True
          noclasses: True
          guess_lang: False
          use_pygments: True
          pygments_style: monokai
    - smarty:
          smart_angled_quotes: True
    - admonition
    - abbr
    - def_list
    - footnotes
nav:
    - Home: index.md
theme: readthedocs
