version: 2
jobs:
    stamp:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: sed -i "s/-dev/-${CIRCLE_BUILD_NUM}/g" package.json
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            - run: cat package.json | jq -r '.version'
            - persist_to_workspace:
                  root: ./
                  paths:
                      - package.json
                      - .npmrc
#     dependencies:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - run: npm install --production
#             - save_cache:
#                   key: dependencies-{{ checksum "package.json" }}
#                   paths:
#                       - /node_modules

#     dev_dependencies:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - run: npm install --only=dev
#             - save_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#                   paths:
#                       - /node_modules

#     docs:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - run: echo "Will generate documentation here"

#     code_review:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - restore_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#             - run: npm run tslint

#     build_dev:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - restore_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#             - run:
#                   ./node_modules/.bin/tsc -p tsconfig.json --skipLibCheck true
#                   --listFiles true --listEmittedFiles true --declaration true
#                   --sourceMap false --inlineSourceMap true --inlineSources true
#             - persist_to_workspace:
#                   root: ./
#                   paths:
#                       - dist/*

#     build_prod:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - restore_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#             - run:
#                   ./node_modules/.bin/tsc -p tsconfig.json --removeComments true
#                   --skipLibCheck true --sourceMap false --listFiles true
#                   --listEmittedFiles true --declaration true
#             - persist_to_workspace:
#                   root: ./
#                   paths:
#                       - dist/*

#     test:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - restore_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#             - restore_cache:
#                   key: dependencies-{{ checksum "package.json" }}
#             - run: npm test

#     coverage_report:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - restore_cache:
#                   key: dev_dependencies-{{ checksum "package.json" }}
#             - restore_cache:
#                   key: dependencies-{{ checksum "package.json" }}
#             - run: npm run coverage
#             - store_artifacts:
#                   path: /code/test-results
#                   destination: prefix
#     deploy_dev:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - attach_workspace:
#                   at: ./
#             - run: npm publish --access public --tag dev --dry-run
#     cache_master:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - attach_workspace:
#                   at: ./
#             - save_cache:
#                   key: dist-{{ CIRCLE_BUILD_NUM }}
#                   paths:
#                       - /node_modules

#     deploy_release:
#         docker:
#             - image: circleci/node:10
#         steps:
#             - checkout
#             - attach_workspace:
#                   at: ./
#             - run: npm publish --access public --dry-run

workflows:
    version: 2
    publish:
        jobs:
            - stamp
#             - dependencies
#             - dev_dependencies
#             - docs
#             - code_review:
#                   requires:
#                       - dev_dependencies
#             - build_dev:
#                   requires:
#                       - dev_dependencies
#                   filters:
#                       branches:
#                           only: develop
#             - build_prod:
#                   requires:
#                       - dev_dependencies
#                   filters:
#                       branches:
#                           only: master
#             - test:
#                   requires:
#                       - build_dev
#                       - build_prod
#                       - dependencies
#             - coverage_report:
#                   requires:
#                       - dev_dependencies
#                       - dependencies

#             - publish_master:
#                   requires:
#                       - stamp
#                   filters:
#                       branches:
#                           only: master
